waystones:
  names: "words" # How to generate waystone names: words, numbers, letters
  max-teleport-distance: 3000 # Max distance a player can teleport with a waystone
  teleport-cooldown: 0 # Cooldown between teleports (in seconds)
  teleport-cost:
    type: none # Cost type: none, xp, item
    levels: 0 # Cost amount for xpLevel
    item: # For item cost
      type: DIAMOND
      amount: 1
  teleport-sound: minecraft:entity.enderman.teleport # Sound played when teleporting

crafting:
  enabled: true # Allow crafting of waystones
  recipe:
    type: shaped # Recipe type: shaped, shapeless
    shape: # If shapeless, doesn't take shape into account, rather only the amount of items
    - 'DGD'
    - 'GWG'
    - 'DGD'
    ingredients:
      D: DIAMOND
      G: GOLD_INGOT
      W: COMPASS